### ISSUE TITLE
Style outlines and overlays on touch/click to match theme

### ISSUE THREAD

**Issue by faheel** [faheel/LiveMark-Editor#4]
When buttons and links are touched or clicked, they have outlines, or overlays, or both which need to be removed (hidden).

**Comment by sagar-kalra** [comment]
i would like to work on this. Can you please elaborate more? Thanks

**Comment by brunopulis** [comment]
@faheel Removing the outline from links and buttons is not a good pratice because the acessibility issues. 
[check this link](http://a11yproject.com/posts/never-remove-css-outlines/). Maybe we think other approach to fix this.

**Comment by faheel** [comment]
@brunopulis Good point! So instead of hiding them, we should modify the way they look to go along with the existing theme.

**Comment by faheel** [comment]
@brunopulis Thanks!
There's just one button in `index.html` with the id `toggle-fab` whose outline needs to be styled to a circular border of a shade of grey (say `#888`), and the light grey overlay that shows up when the button is clicked/touched needs to be hidden.

**Comment by faheel** [comment]
Fixed in the latest versions of Material Components Web.
